#!/usr/bin/env bash
set -e

echo "=== Wæcnan Testnet Bootstrap ==="
echo "Building workspace..."
cargo build --workspace --release 2>&1 | tail -5

echo ""
echo "Genesis block parameters:"
echo "  Network:    Wæcnan Testnet"
echo "  Ticker:     WAEC"
echo "  P2P Port:   19334"
echo "  RPC Port:   19335"
echo "  Block time: 120 seconds"
echo "  Algorithm:  RandomX (CPU-only)"
echo "  Privacy:    MLSAG ring signatures (ring=11)"
echo "  Fee burn:   Yes (100% of fees burned)"
echo ""
echo "Node 1 config:"
echo "  data_dir: /tmp/waecan-node1"
echo "  p2p_port: 19334"
echo "  rpc_port: 19335"
echo ""
echo "Node 2 config:"
echo "  data_dir: /tmp/waecan-node2"
echo "  p2p_port: 19336"
echo "  rpc_port: 19337"
echo ""
echo "Node 3 config:"
echo "  data_dir: /tmp/waecan-node3"
echo "  p2p_port: 19338"
echo "  rpc_port: 19339"
echo ""
echo "Testnet ready. Run each node with:"
echo "  cargo run -p waecan-node -- --data-dir /tmp/waecan-nodeN"
echo ""
echo "=== Wæcnan testnet bootstrap complete ==="
